<wsdl:definitions
     name="PolingInfo"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JenkinsTest/Test/PolingInfo"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/JenkinsTest/Test/PolingInfo"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PolingInfo"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="PolingInfo_plt" >
    <plt:role name="PolingInfo_role" >
      <plt:portType name="tns:PolingInfo_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PolingInfo" schemaLocation="PolingInfo_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="InformacionCollection_msg">
        <wsdl:part name="InformacionCollection" element="top:InformacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="PolingInfo_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:InformacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
